# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WordProcessor(object):
    def setupUi(self, WordProcessor):
        WordProcessor.setObjectName("WordProcessor")
        WordProcessor.resize(789, 637)
        self.centralwidget = QtWidgets.QWidget(WordProcessor)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_2.addWidget(self.textEdit_2, 1, 3, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 1, 1, 2, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 2, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 2, 2, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 2, 3, 1, 1)
        WordProcessor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WordProcessor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFormat = QtWidgets.QMenu(self.menubar)
        self.menuFormat.setObjectName("menuFormat")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        WordProcessor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WordProcessor)
        self.statusbar.setObjectName("statusbar")
        WordProcessor.setStatusBar(self.statusbar)
        self.actionNew_File = QtWidgets.QAction(WordProcessor)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionOpen = QtWidgets.QAction(WordProcessor)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(WordProcessor)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(WordProcessor)
        self.actionExit.setObjectName("actionExit")
        self.actionCopy = QtWidgets.QAction(WordProcessor)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(WordProcessor)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(WordProcessor)
        self.actionPaste.setObjectName("actionPaste")
        self.actionFont = QtWidgets.QAction(WordProcessor)
        self.actionFont.setObjectName("actionFont")
        self.actionColor = QtWidgets.QAction(WordProcessor)
        self.actionColor.setObjectName("actionColor")
        self.actionBold = QtWidgets.QAction(WordProcessor)
        self.actionBold.setObjectName("actionBold")
        self.actionItalic = QtWidgets.QAction(WordProcessor)
        self.actionItalic.setObjectName("actionItalic")
        self.actionSpell_Check = QtWidgets.QAction(WordProcessor)
        self.actionSpell_Check.setObjectName("actionSpell_Check")
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionSpell_Check)
        self.menuFormat.addAction(self.actionFont)
        self.menuFormat.addAction(self.actionColor)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFormat.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(WordProcessor)
        QtCore.QMetaObject.connectSlotsByName(WordProcessor)

    def retranslateUi(self, WordProcessor):
        _translate = QtCore.QCoreApplication.translate
        WordProcessor.setWindowTitle(_translate("WordProcessor", "WordProcessor"))
        self.label_2.setText(_translate("WordProcessor", "Text Area"))
        self.textEdit_2.setStatusTip(_translate("WordProcessor", "Suggestion Box"))
        self.textEdit.setStatusTip(_translate("WordProcessor", "Text Editor"))
        self.textEdit.setHtml(_translate("WordProcessor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("WordProcessor", "Sugesstions"))
        self.pushButton_5.setStatusTip(_translate("WordProcessor", "Correct the spellings"))
        self.pushButton_5.setText(_translate("WordProcessor", "Correct"))
        self.pushButton.setStatusTip(_translate("WordProcessor", "Click to check spellings"))
        self.pushButton.setText(_translate("WordProcessor", "Check"))
        self.pushButton_6.setStatusTip(_translate("WordProcessor", "Ignore the error"))
        self.pushButton_6.setText(_translate("WordProcessor", "Ignore"))
        self.pushButton_2.setStatusTip(_translate("WordProcessor", "Add the words to Dictionary"))
        self.pushButton_2.setText(_translate("WordProcessor", "Add to Dict"))
        self.menuFile.setTitle(_translate("WordProcessor", "File"))
        self.menuEdit.setTitle(_translate("WordProcessor", "Edit"))
        self.menuFormat.setTitle(_translate("WordProcessor", "Format"))
        self.menuHelp.setTitle(_translate("WordProcessor", "Help"))
        self.actionNew_File.setText(_translate("WordProcessor", "New File"))
        self.actionOpen.setText(_translate("WordProcessor", "Open"))
        self.actionSave.setText(_translate("WordProcessor", "Save"))
        self.actionExit.setText(_translate("WordProcessor", "Exit"))
        self.actionCopy.setText(_translate("WordProcessor", "Copy"))
        self.actionCut.setText(_translate("WordProcessor", "Cut"))
        self.actionPaste.setText(_translate("WordProcessor", "Paste"))
        self.actionFont.setText(_translate("WordProcessor", "Font"))
        self.actionColor.setText(_translate("WordProcessor", "Color"))
        self.actionBold.setText(_translate("WordProcessor", "Bold"))
        self.actionItalic.setText(_translate("WordProcessor", "Italic"))
        self.actionSpell_Check.setText(_translate("WordProcessor", "Spell Check"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WordProcessor = QtWidgets.QMainWindow()
    ui = Ui_WordProcessor()
    ui.setupUi(WordProcessor)
    WordProcessor.show()
    sys.exit(app.exec_())
